--	//CREANDO BASE DE DATOS
--CREATE DATABASE SMARTECH;
	
	--//USANDO BASE DE DATOS
--USE SMARTECH

--//CREANDO LA TABLA

/*CREATE TABLE PRODUCTOS(

ID INT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_NAME VARCHAR(30),
PRICE INT
);*/

/* INSERT INTO PRODUCTOS (PRODUCT_NAME, PRICE) VALUES ('HP 2015','200');
INSERT INTO PRODUCTOS (PRODUCT_NAME, PRICE) VALUES ('TOSHIBA','200');
INSERT INTO PRODUCTOS (PRODUCT_NAME, PRICE) VALUES ('AIRPOD','100');
INSERT INTO PRODUCTOS (PRODUCT_NAME, PRICE) VALUES ('IPHONE CASE','50');
INSERT INTO PRODUCTOS (PRODUCT_NAME, PRICE) VALUES ('ALEXA BOCINA','50');
INSERT INTO PRODUCTOS (PRODUCT_NAME, PRICE) VALUES ('IPHONE CHARGER','50');
INSERT INTO PRODUCTOS (PRODUCT_NAME, PRICE) VALUES ('SMARTWATCH','100');

*/
